version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postgres
      - PGDATABASE=todo_app
      - PGPORT=5432
      - PORT=5000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
